### ISSUE TITLE
No sourcecode in repository

### ISSUE THREAD

**Issue by NelDav** [bemeurer/aks#1]
Hi lovesegfault,

I am a bit confused, your `aks` module for rust was downloaded more than 390 times, but I can't find any libary or sourcecode. Your repository is nearly empty and there are only 7 commits. Am I looking at the wrong place?

**Comment by lovesegfault** [comment]
You're not, this is an abandoned project that I'm planning on revisiting when I'm on vacation. I plan my projects ahead of time through the year and work on them when I get a break from work.

Sorry for the confusion, if you're interested in implementing this I can point you to the paper :)

**Comment by NelDav** [comment]
Ok, thank you. I think I will pass. I am not familiar with rust at all. I am learning it by my self and don't think, that my skills are good enougth to create a good implementation.
